### ISSUE TITLE
paper issue

### ISSUE THREAD

**Issue by pengyiwu** [hq-jiang/instance-segmentation-with-discriminative-loss-tensorflow#10]
hello ,i have read the paper"Towards End-to-End Lane Detection: an Instance Segmentation Approach"
do you know what's the meaning of the "bounded inverse class weighting"(to solve the problem that the lane lines area is too small).  i can not find the detailed explanation about the "bounded inverse class weighting"
thanks so much!

**Comment by hq-jiang** [comment]
As I understand, you just weight the classes anti proportional to their frequency and have some cutoff value. I think, I did the same but hardcoded the values

**Comment by pengyiwu** [comment]
i just want to use the binary segmentation branch, how to change your code? the meanshift cluster is so slow.
thanks a lot!
