### ISSUE TITLE
semantic_segmentation code

### ISSUE THREAD

**Issue by wuyipengdashuaige** [hq-jiang/instance-segmentation-with-discriminative-loss-tensorflow#12]
Hello ,thanks a lot for your code . In my experiment，the inference time is about 60ms ,but the cluster time is more than 4s.  so I only want to do the binary segmentation. Is there  complete code for semantic segmentation? I got a trained model by your 'transfer_semantic.py' and failed in writing the inference and evaluation code.
Have a nice day!

**Comment by hq-jiang** [comment]
Unfortunately, there is none. I would also have to rewrite it myself. I thought people would not be interested in this, since binray segmentation is pretty much solved. You could look at https://github.com/kwotsin/TensorFlow-ENet for inference.

**Comment by wuyipengdashuaige** [comment]
~^o^~thanks so much for your advice . i need a real-time lane detection in my coursework. i can filter the binary segmentation and then do the means-shift cluster . however i will try to adapt the network to output a lower resolution at first. since 端对端的检测貌似更好
